finalize arabic version
metanorma/isodoc pull request #305
Opened 2021-06-27 17:28 UTC by AhMohsen46

2021-06-27 17:31 UTC, ronaldtse requested changes

2021-06-27 17:31 UTC, ronaldtse commented on lib/isodoc-yaml/i18n-ar.yaml
> +termnote: ملاحظة ٪ للقيد
`٪` need to be changed back to `%` because it is used for interpolation.

2021-06-27 17:31 UTC, ronaldtse commented on lib/isodoc-yaml/i18n-ar.yaml
> +    pl: ملاحظات ٪ للقيد
As above.

2021-06-27 17:31 UTC, ronaldtse commented on lib/isodoc-yaml/i18n-ar.yaml
> +  <p> لأغراض هذا المستند ، تنطبق المصطلحات والتعريفات الواردة في%٪. </ p>
As below regarding `%`.

2021-06-27 22:47 UTC, AhMohsen46 commented
@ronaldtse there is an error that I don't get

what I've done was replacing all the ٪ with %
anything special about % with arabic that am not aware of?
worth mentioning that ٪ is the arabic version of %, it has a Arabic mapping, both look the exact same though, just a circle instead of a dot

2021-06-28 09:23 UTC, opoudjis commented
The replacement is done in my code, and my code will differentiate between ASCII % and Arabic ٪. That's OK, I'll take care of it.

2021-06-28 09:24 UTC, merged